create table if not exists public.student_schedule_freezes (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    student text not null,
    start_date date,
    end_date date,
    reason text,
    note text,
    active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists idx_student_schedule_freezes_user_active
    on public.student_schedule_freezes (user_id, active, student);

create index if not exists idx_student_schedule_freezes_dates
    on public.student_schedule_freezes (user_id, start_date, end_date)
    where active = true;

alter table public.student_schedule_freezes enable row level security;

drop policy if exists "student_schedule_freezes_select_own" on public.student_schedule_freezes;
create policy "student_schedule_freezes_select_own"
    on public.student_schedule_freezes
    for select
    using (auth.uid() = user_id);

drop policy if exists "student_schedule_freezes_insert_own" on public.student_schedule_freezes;
create policy "student_schedule_freezes_insert_own"
    on public.student_schedule_freezes
    for insert
    with check (auth.uid() = user_id);

drop policy if exists "student_schedule_freezes_update_own" on public.student_schedule_freezes;
create policy "student_schedule_freezes_update_own"
    on public.student_schedule_freezes
    for update
    using (auth.uid() = user_id)
    with check (auth.uid() = user_id);

drop policy if exists "student_schedule_freezes_delete_own" on public.student_schedule_freezes;
create policy "student_schedule_freezes_delete_own"
    on public.student_schedule_freezes
    for delete
    using (auth.uid() = user_id);
