create table if not exists public.explorer_moves (
    id bigint generated by default as identity primary key,
    resource_type text not null,
    tool_key text not null,
    source_section text not null default 'explore_ai_tools',
    title text not null default '',
    subject text not null default '',
    topic text not null default '',
    learner_stage text not null default '',
    level_or_band text not null default '',
    language text not null default '',
    preview_text text not null default '',
    payload_json jsonb not null default '{}'::jsonb,
    meta_json jsonb not null default '{}'::jsonb,
    anonymous_session_id text not null default '',
    status text not null default 'pending',
    published_table text not null default '',
    published_record_id text,
    published_at timestamptz,
    admin_notes text not null default '',
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists explorer_moves_status_created_idx
    on public.explorer_moves (status, created_at desc);

create index if not exists explorer_moves_resource_created_idx
    on public.explorer_moves (resource_type, created_at desc);

create index if not exists explorer_moves_anon_session_idx
    on public.explorer_moves (anonymous_session_id);