create table if not exists public.teacher_review_requests (
  id bigint generated by default as identity primary key,
  teacher_id uuid not null references auth.users(id) on delete cascade,
  student_id uuid not null references auth.users(id) on delete cascade,
  subject_key text not null default '',
  subject_label text not null default '',
  practice_session_id bigint not null references public.practice_sessions(id) on delete cascade,
  assignment_id bigint references public.teacher_assignments(id) on delete set null,
  source_type text not null default '',
  source_id bigint,
  title text not null default '',
  status text not null default 'requested' check (status in ('requested', 'reviewed', 'closed')),
  request_note text not null default '',
  teacher_feedback text not null default '',
  review_payload jsonb not null default '{}'::jsonb,
  override_score_pct numeric(5,1),
  requested_at timestamptz not null default now(),
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists teacher_review_requests_teacher_session_uidx
  on public.teacher_review_requests (teacher_id, practice_session_id);

create index if not exists teacher_review_requests_student_idx
  on public.teacher_review_requests (student_id, requested_at desc);

create index if not exists teacher_review_requests_teacher_idx
  on public.teacher_review_requests (teacher_id, requested_at desc);

create index if not exists teacher_review_requests_assignment_idx
  on public.teacher_review_requests (assignment_id);

alter table public.teacher_review_requests enable row level security;

drop policy if exists "Teacher/student read own review requests" on public.teacher_review_requests;
create policy "Teacher/student read own review requests"
on public.teacher_review_requests
for select
using (auth.uid() = teacher_id or auth.uid() = student_id);

drop policy if exists "Student creates own review requests" on public.teacher_review_requests;
create policy "Student creates own review requests"
on public.teacher_review_requests
for insert
with check (auth.uid() = student_id);

drop policy if exists "Teacher updates own review requests" on public.teacher_review_requests;
create policy "Teacher updates own review requests"
on public.teacher_review_requests
for update
using (auth.uid() = teacher_id)
with check (auth.uid() = teacher_id);
