-- ============================================================
-- CLASSIO — Production subscriptions, usage, and admin controls
-- Run in Supabase SQL editor before enabling paid launch features.
-- ============================================================

-- Profiles launch fields. Existing app uses profiles.user_id as the app user key.
alter table profiles
    add column if not exists role text default 'teacher',
    add column if not exists current_plan text default 'free',
    add column if not exists subscription_status text default 'free',
    add column if not exists account_status text default 'active',
    add column if not exists admin_notes text;

-- If an older role check constraint only allowed teacher/student/tutor, replace it
-- with production roles needed for admin and school accounts.
do $$
declare
    constraint_name text;
begin
    select conname into constraint_name
    from pg_constraint
    where conrelid = 'profiles'::regclass
      and contype = 'c'
      and pg_get_constraintdef(oid) like '%role%teacher%student%'
    limit 1;

    if constraint_name is not null then
        execute format('alter table profiles drop constraint %I', constraint_name);
    end if;
end $$;

alter table profiles drop constraint if exists profiles_role_allowed;

alter table profiles
    add constraint profiles_role_allowed
    check (role in ('admin', 'teacher', 'student', 'school_admin', 'tutor'));

-- Launch plans are intentionally data-driven so pricing/limits can change without code deploys.
create table if not exists plans (
    id text primary key,
    name text not null,
    price integer,
    billing_interval text not null default 'month',
    features_json jsonb not null default '{}'::jsonb,
    limits_json jsonb not null default '{}'::jsonb,
    active boolean not null default true,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

insert into plans (id, name, price, billing_interval, features_json, limits_json, active)
values
    ('free', 'Free', 0, 'month',
     '{"ai_tools": true, "pdf_export": true, "premium_tools": false, "school_admin": false}',
     '{"ai_generations": 10, "pdf_exports": 3, "students_count": 5, "classes_count": 20}', true),
    ('teacher_pro', 'Teacher Pro', 1900, 'month',
     '{"ai_tools": true, "pdf_export": true, "premium_tools": true, "school_admin": false}',
     '{"ai_generations": 250, "pdf_exports": 100, "students_count": 75, "classes_count": 500}', true),
    ('school', 'School Plan', null, 'month',
     '{"ai_tools": true, "pdf_export": true, "premium_tools": true, "school_admin": true}',
     '{"ai_generations": 2000, "pdf_exports": 1000, "students_count": 1000, "classes_count": 10000}', true),
    ('beta_lifetime', 'Beta / Lifetime', 0, 'lifetime',
     '{"ai_tools": true, "pdf_export": true, "premium_tools": true, "school_admin": false}',
     '{"ai_generations": 1000, "pdf_exports": 500, "students_count": 500, "classes_count": 5000}', true)
on conflict (id) do update set
    name = excluded.name,
    price = excluded.price,
    billing_interval = excluded.billing_interval,
    features_json = excluded.features_json,
    limits_json = excluded.limits_json,
    active = excluded.active,
    updated_at = now();

create table if not exists user_subscriptions (
    user_id text primary key,
    plan_id text not null references plans(id),
    subscription_status text not null default 'free',
    provider_customer_id text,
    provider_subscription_id text,
    trial_end timestamptz,
    current_period_end timestamptz,
    cancel_at_period_end boolean not null default false,
    manual_override boolean not null default false,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists payment_events (
    id bigint generated by default as identity primary key,
    provider text not null,
    event_type text not null,
    payload jsonb not null default '{}'::jsonb,
    processed boolean not null default false,
    created_at timestamptz not null default now()
);

create table if not exists usage_tracking (
    user_id text primary key,
    ai_generations integer not null default 0,
    pdf_exports integer not null default 0,
    students_count integer not null default 0,
    classes_count integer not null default 0,
    monthly_reset_date date not null default current_date,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists admin_overrides (
    id bigint generated by default as identity primary key,
    user_id text not null,
    override_type text not null,
    reason text,
    created_by text,
    expires_at timestamptz,
    created_at timestamptz not null default now()
);

create index if not exists idx_user_subscriptions_provider_customer_id on user_subscriptions(provider_customer_id);
create index if not exists idx_payment_events_type_created_at on payment_events(event_type, created_at desc);
create index if not exists idx_admin_overrides_user_id on admin_overrides(user_id);
